# Site settings
languageCode: en-us
pluralizeListTitles: false
title: GameBreaks

# Enter your tracking code to enable Google Analytics
googleAnalytics: ""

module:
  imports:
    path: github.com/pieterjandesmedt/hugo-theme-gamebreaks
    # path: /Users/pieterjan/Sites/hugo-themes/gamebreaks

defaultContentLanguage: nl
defaultContentLanguageInSubdir: true
languages:
  nl:
    contentDir: content/nl
    disabled: false
    languageCode: nl-BE
    languageDirection: ltr
    languageName: Nederlands
    params:
      readMoreButton: Ontdek
      hero:
        # Main hero title
        title: Take Breaks. Play Games.
        # Hero subtitle (optional)
        subtitle: GameBreaks helpt bedrijven om hun teams performanter te maken.
        # Button text
        buttontext: Leer hoe
        # Where the main hero button links to
        buttonlink: "#betere-teams-bouwen"
        # Hero image (from static/images/___)
        image: illustrations/team-spirit-pana.svg
        # Footer logos (from static/images/logos/clients/*.svg)
        # urls are optional
        clientlogos:
        # - logo: tabor.svg
        #   url: https://www.taborgroep.be/nl
        # - logo: starterslabo.png
        #   url: https://starterslabo.be/
      section2:
        title: Betere teams bouwen
        subtitle: door spellen te spelen
      section3:
        title: Wat wij bieden
        subtitle: om teams beter te maken
      section4:
        title: Onze klanten houden van ons!
        subtitle: Enkele getuigenissen
        clients:
        - name: Geertrui
          quote: Het was een activiteit waarin je zowel veel spelplezier uithaalt als je een gevoel van verbondenheid met je team geeft. Het was een cool spel met veel mooie details waar ieder iets kon uit halen wat hij graag doet.
          job: Consultant Infrastructuur
          img: Geertrui Vandist.jpg
        - name: Christophe
          quote: In begin was iedereen wat afwachtend, maar uiteindelijk werkten alle collega’s samen om het doel te bereiken en heerste er een echt teamgevoel. Het was dus zeer geslaagd.
          job: Consultant Duurzame Infrastructuur
          img: Christophe_0.jpg
        - name: Hannelore
          quote: Toffe manier om je collega’s snel op een andere manier te leren kennen. Het zat goed in elkaar met verschillende lagen, zonder dat het te ingewikkeld werd. Het werd goed begeleid en het bouwt op in verschillende rondes.
          job: Consultant Talent & Organisatie
          img: Hannelore.jpg
        - name: Chris
          quote: Ik ontdekte mijn enthousiasmerende slavendrijverskills 😉. Ik heb mijn collega’s van de technische dienst leren kennen en nu organiseren wij samen het volgende werkevent.
          job: Project Manager
          img: Chris DC 1e keuze.jpg
        - name: Fadi
          quote: Vanaf de eerste smaak van chaos leren we ons teamworkrecept verfijnen, waarbij we de hitte van fouten omzetten in de pruttelende bouillon van verbetering. In deze culinaire reis rijzen leiders op als bedreven koks, waardoor het restaurant van chaos verandert in een feest van plezier en samenwerking.
          job: Life Science Business Unit Executive
          img: fadi.jpg
        - name: Gerd
          quote: Zeer bruikbaar om het belang van teamwork en verdeling van taken en zoektocht naar efficiëntie aan te kaarten 👍
          job: Operations Manager Utilities
          img: gerd.jpg
      section5:
        title: Laat ons iets weten
        subtitle: We willen graag met je samenwerken
        buttonText: Stuur bericht
        name: Je naam
        email: Je email-adres
        message: Schrijf iets...
        action: /nl/succes/
      sectionGame:
        price: Prijs
        duration: Tijdsduur
        languages: Talen
        date: Datum
        participants: Aantal deelnemers
        to: tot
        message: Bijkomende opmerking of vragen...
        buttonText: Vraag offerte aan
        cancelText: Annuleren
      # Customizable navbar. For a dropdown, add a "sublinks" list.
      navbar:
      - title: Spellen
        url: /nl/spellen
      # - title: Formules
      #   url: /nl/formules
      - title: Contact
        url: '/nl/contact'
      footer:
        # Logo (from /images/logos/___)
        logo: gamebreaks-logo-yellow.png
        # Social media links (GitHub, Twitter, etc.). All are optional.
        socialmedia:
          # Icons are from Font Awesome
        - link: https://www.instagram.com/gamebreaks.be/
          icon: instagram
        # - link: https://dribbble.com/#
        #   icon: dribbble
        - link: https://facebook.com/#
          icon: facebook
        # - link: https://twitter.com/StefMa91
        #   icon: twitter
        # - link: https://bitbucket.org/#
        #   icon: bitbucket
        # Social Media Title
        socialmediatitle: Volg ons
        quicklinks:
          column1:
            title: "Product"
            links:
            - text: Onze Spellen
              link: /nl/spellen
            # - text: Onze Formules
            #   link: /nl/formules
          # column2:
          #   title: "Documentatie"
          #   section: "docs"
          column3:
            title: "Blog"
            links:
            - text: Laatste Nieuws
              link: /nl/blog
            - text: Tech artikels
              link: /nl/tech

    weight: 1
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      readMoreButton: Discover
      hero:
        # Main hero title
        title: Take Breaks. Play Games.
        # Hero subtitle (optional)
        subtitle: GameBreaks helps companies build better teams.
        # Button text
        buttontext: Learn how
        # Where the main hero button links to
        buttonlink: "#building-better-teams"
        # Hero image (from static/images/___)
        image: illustrations/team-spirit-pana.svg
        # Footer logos (from static/images/logos/clients/*.svg)
        # urls are optional
        clientlogos:
        # - logo: tabor.svg
        #   url: https://www.taborgroep.be/nl
        # - logo: starterslabo.png
        #   url: https://starterslabo.be/
      section2:
        title: Building better teams
        subtitle: by playing games
      section3:
        title: What we offer you
        subtitle: to accomplish better teams
      section4:
        title: Our clients love us!
        subtitle: Some testimonials
        clients:
        - name: Geertrui
          quote: It was an activity in which you both get a lot of game fun out of and a sense of belonging to your team. It was a cool game with a lot of nice details where each one could get something out of it that they like.
          job: Consultant Infrastructuur
          img: Geertrui Vandist.jpg
        - name: Christophe
          quote: In the beginning everyone was a bit hesitant, but in the end all colleagues worked together to achieve the goal and there was a real team feeling. So it was very successful.
          job: Consultant Duurzame Infrastructuur
          img: Christophe_0.jpg
        - name: Hannelore
          quote: Cool way to quickly get to know your colleagues in a different way. It was well put together with different layers without getting too complicated. It was well guided and it builds up in different rounds.
          job: Consultant Talent & Organisatie
          img: Hannelore.jpg
        - name: Chris
          quote: I discovered my enthusiastic slave-driving skills 😉. I got to know my colleagues in technical services and now we are organizing the next work event together.
          job: Project Manager
          img: Chris DC 1e keuze.jpg
        - name: Fadi
          quote: From the first taste of chaos, we learn to refine our teamwork recipe, turning the heat of mistakes into the simmering broth of improvement. In this culinary journey, leaders rise as adept cooks, transforming the restaurant from chaos into a feast of fun and collaboration.
          job: Life Science Business Unit Executive
          img: fadi.jpg
        - name: Gerd
          quote: Very useful to raise the importance of teamwork and division of tasks and quest for efficiency 👍
          job: Operations Manager Utilities
          img: gerd.jpg
      section5:
        title: Drop us a line or two
        subtitle: We'd love to hear from you
        buttonText: Send Message
        action: /en/success/
        # method: POST
      sectionGame:
        price: Price
        duration: Duration
        languages: Languages
        date: Date
        particpants: Number of participants
        to: to
        message: Additional remarks or questions...
        buttonText: Ask offer
        cancelText: Cancel
      navbar:
      - title: Games
        url: /en/games
      # - title: Formulas
      #   url: /en/formulas
      - title: Contact
        url: '/en/contact'
      footer:
        # Logo (from /images/logos/___)
        logo: gamebreaks-logo-yellow.png
        # Social media links (GitHub, Twitter, etc.). All are optional.
        socialmedia:
          # Icons are from Font Awesome
        - link: https://www.instagram.com/gamebreaks.be/
          icon: instagram
        # - link: https://dribbble.com/#
        #   icon: dribbble
        - link: https://facebook.com/#
          icon: facebook
        # - link: https://twitter.com/StefMa91
        #   icon: twitter
        # - link: https://bitbucket.org/#
        #   icon: bitbucket
        # Social Media Title
        socialmediatitle: Follow us
        quicklinks:
          column1:
            title: "Product"
            links:
            - text: Our games
              link: /en/games
            # - text: Our formulas
            #   link: /en/formulas
          # column2:
          #   title: "Docs"
          #   section: "docs"
          column3:
            title: "Blog"
            links:
            - text: Latest News
              link: /en/blog
            - text: Tech Articles
              link: /en/tech
    weight: 2

params:
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name: GameBreaks
  description: Take Breaks. Play Games.

  # Link custom assets relative to /static
  custom_css:
  custom_js:
    - /js/scripts.js

  # Button texts
  learnmore: Meer &rarr;

  # 404 error customization
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)

googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/gamebreaks-logo-blue.png
    link: /
    # Default width/height. Uncomment if you need to change
    width: 50
    height: 50
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Take Breaks. Play Games.
    # Hero subtitle (optional)
    subtitle: Lorem ipsum sit dolor amet is dummy text used by the typography industry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/team-spirit-pana.svg
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    clientlogos:
    - logo: tabor
      url: https://www.taborgroep.be/nl
    - logo: tribe
      url: https://stefma.github.io/hugo-fresh/
    - logo: kromo
      url: https://github.com/StefMa/hugo-fresh
    - logo: infinite
      url: https://hugo-fresh.vercel.app/
    - logo: gutwork
      url: https://bulma.io/
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Spellen
    url: /nl/spellen
  - title: Formules
    url: /
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: Building better teams
    subtitle: by playing games
  section3:
    title: What we offer you
    subtitle: to accomplish better teams
  section4:
    title: Onze klanten houden van ons!
    subtitle: Enkele getuigenissen
    clients:
    - name: Geertrui
      quote: Het was een activiteit waarin je zowel veel spelplezier uithaalt als je een gevoel van verbondenheid met je team geeft. Het was een cool spel met veel mooie details waar ieder iets kon uit halen wat hij graag doet.
      job: Consultant Infrastructuur
      img: 1
    - name: Christophe
      quote: In begin was iedereen wat afwachtend, maar het heeft het doel bereikt, want uiteindelijk werkten alle collega’s samen om het doel te bereiken en heerste er een echt teamgevoel. Het was dus zeer geslaagd.
      job: Consultant Duurzame Infrastructuur
      img: 2
    - name: Hannelore
      quote: Toffe manier om je collega’s snel op een andere manier te leren kennen. Het zat goed in elkaar met verschillende lagen, zonder dat het te ingewikkeld werd. Het werd goed begeleid en het bouwt op in verschillende rondes.
      job: Consultant Talent & Organisatie
      img: 3
    - name: Hannelore
      quote: Toffe manier om je collega’s snel op een andere manier te leren kennen. Het zat goed in elkaar met verschillende lagen, zonder dat het te ingewikkeld werd. Het werd goed begeleid en het bouwt op in verschillende rondes.
      job: Consultant Talent & Organisatie
      img: 3
    - name: Chris
      quote: Ik ontdekte tijdens het ‘slicen mijn enthousiasmerende slavendrijverskills 😉. Ik heb mijn collega’s van de technische dienst leren kennen en nu organiseren wij samen het volgende werkevent.
      img: 4
  section5:
    title: Drop us a line or two
    subtitle: We'd love to hear from you
    buttonText: Send Message
    # action: https://formspree.io/f/<form_id>
    # method: POST
  footer:
    # Logo (from /images/logos/___)
    logo: gamebreaks-logo-yellow.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      # Icons are from Font Awesome
    - link: https://www.instagram.com/gamebreaks.be/
      icon: instagram
    # - link: https://dribbble.com/#
    #   icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    # - link: https://twitter.com/StefMa91
    #   icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
